### ISSUE TITLE
Git missing in container required by code in a Tox test - what now?

### ISSUE THREAD

**Issue by bittner** [themattrix/docker-tox#10]
I have a Python project that I run [a few tests for](https://github.com/painless-software/painless-continuous-delivery/tree/master/tests/unit) with the `docker-tox` container. In the tests the [cookiecutter](https://pypi.python.org/pypi/cookiecutter/1.5.0) executable generates the skeleton provided by my project.

This used to work fine. Now, after a [specific change](https://github.com/painless-software/painless-continuous-delivery/commit/901618d697f991ad249a98117944d402725d1933#diff-c2ff4f6aba93d62ed9a32a6dda454da6R131), I have the problem that the `git` executable is not found:
``` bash
/bin/sh: 1: git: not found
```
I don't really understand why the cookiecutter is affected by the change. Please see the [failing build on Bitbucket Pipelines](https://bitbucket.org/painless-software/painless-continuous-delivery/addon/pipelines/home#!/results/%7Be39823b3-ed92-428a-94ef-ea5a5795bb83%7D) (public) or [on Codeship](https://app.codeship.com/projects/174831/builds/871cbcac-b8c8-4e4d-8315-3f2ffaee4f27) (requires an account) for reference.

If it should be necessary to install Git on the container what would you recommend to do? Should I place a PR to add Git to the image, generally?

**Comment by themattrix** [comment]
The root cause is that I switched the base image to [themattrix/pyenv](https://github.com/themattrix/docker-pyenv), which doesn't include git. Since nothing in this image requires git, I'd prefer to leave it out.

My recommendation would be to create a Dockerfile that looks something like this:

```Dockerfile
FROM themattrix/tox

RUN apt-get update -y && 
    apt-get install -y --no-install-recommends git ca-certificates &&
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Since you're using Bitbucket Pipelines, it seems you'll need to point your build directly at an image. The easiest way would probably be to create a repo with the above Dockerfile and use it to create an [automated build in Docker Hub](https://docs.docker.com/docker-hub/builds/). Alternatively, you could add the above Dockerfile to your existing Bitbucket repo and point the automated build there.

Having your own image will definitely give you the most flexibility, in case you need to add more dependencies in the future.

**Comment by bittner** [comment]
Thanks for the hint. Sounds like the best choice, so I've prepared everything.

However, [the build fails](https://hub.docker.com/r/painless/tox/builds/bwqaybju793ja3cyyzuwbwf/), because it expects to run the actual tox test run:
```
Step 1 : COPY install-prereqs*.sh requirements*.txt tox.ini /app/

lstat tox.ini: no such file or directory
```
I'm a bit puzzled, something's missing. How do we fix that?

**Comment by themattrix** [comment]
Ah...my mistake. The `ONBUILD` commands in this Dockerfile require that `tox.ini` exists. The tox environments are created and baked into the image so they don't have to be recreated on every run.

It seems what you need is an intermediate image: something like themattrix/tox, but without the `ONBUILD` commands. I've now created just such an image: [themattrix/tox-base](https://github.com/themattrix/docker-tox-base). Try switching your base image to that.

**Comment by bittner** [comment]
This seems to work fine! :tada:  Awesome, thank you!

Everyone needing Git too can now use the [painless/tox](https://hub.docker.com/r/painless/tox/) image.

Thanks Matthew!
